# Site settings
title: Katy Huff
email: katyhuff@gmail.com
description: "Website of Katy Huff, nuclear engineer."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://katyhuff.github.io" # the base hostname & protocol for your site
twitter_username: katyhuff
github_username: katyhuff

# Agency color settings
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333
  transparent: rgba(24,24,24,0.7)

# Build settings
markdown: kramdown
permalink: pretty

# Jekyll Scholar
scholar:
  style: chicago-author-date
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibliography

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
  
  repository: papers
