# Site settings
title: Katy Huff
email: katyhuff@gmail.com
description: "Website of Katy Huff, nuclear engineer."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://katyhuff.github.io" # the base hostname & protocol for your site
twitter_username: katyhuff
github_username: katyhuff

# Build settings
markdown: kramdown
