# Site settings
title: Katy Huff
email: katyhuff@gmail.com
description: "Website of Katy Huff, nuclear engineer."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://katyhuff.github.io" # the base hostname & protocol for your site
twitter_username: katyhuff
github_username: katyhuff

# Agency color settings
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333
  transparent: rgba(24,24,24,0.7)

# Build settings
markdown: kramdown
permalink: pretty
